name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash  # Install Bun via curl

      - name: Install dependencies
        run: |
          bun install  # Install dependencies using Bun

      - name: Run ESLint
        run: |
          bun exec eslint . --ext .ts,.tsx,.js,.jsx  # Adjust extensions as needed

      - name: Run Stylelint (if using stylelint)
        run: |
          bun exec stylelint "**/*.css"  # Run Stylelint with Bun

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash  # Install Bun via curl

      - name: Install dependencies
        run: |
          bun install  # Install dependencies using Bun

      - name: Build the project
        run: |
          bun build src/**/*.tsx --outdir dist --target bun  # Replace with your actual build command

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash  # Install Bun via curl

      - name: Install dependencies
        run: |
          bun install  # Install dependencies using Bun

      - name: Run tests
        run: |
          bun test  # Run your tests with Bun
